In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime,date

In [2]:
#loading the customer data from the excel file

cust_address=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Customer_Segmentation/Raw_data (1).xlsx',sheet_name='CustomerAddress')

In [3]:
#Checking first 5 records from Customer Address Data

cust_address.head(5)

,customer_id,address,postcode,state,country,property_valuation
0,1,060 Morning Avenue,2016,New South Wales,Australia,10
1,2,6 Meadow Vale Court,2153,New South Wales,Australia,10
2,4,0 Holy Cross Court,4211,QLD,Australia,9
3,5,17979 Del Mar Point,2448,New South Wales,Australia,4
4,6,9 Oakridge Court,3216,VIC,Australia,9

In [4]:
cust_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         3999 non-null   int64
 1   address             3999 non-null   object
 2   postcode            3999 non-null   int64
 3   state               3999 non-null   object
 4   country             3999 non-null   object
 5   property_valuation  3999 non-null   int64
dtypes: int64(3), object(3)
memory usage: 187.6+ KB

#Total Records

In [5]:
print("Total records (rows) in the dataset: {}".format(cust_address.shape[0]))
print("Total records (columns) in the dataset: {}".format(cust_address.shape[1]))

Total records (rows) in the dataset: 3999
Total records (columns) in the dataset: 6

#Numeric columns and Non-Numeric columns

In [6]:
#select  numeric columns
df_numeric=cust_address.select_dtypes(include=[np.number])
numeric_cols=df_numeric.columns.values
print("The numeric columns are: {}".format(numeric_cols))

#select non-numeric columns
df_non_numeric=cust_address.select_dtypes(exclude=[np.number])
non_numeric_cols=df_non_numeric.columns.values
print("The non-numeric columns are : {}".format(non_numeric_cols))

The numeric columns are: ['customer_id' 'postcode' 'property_valuation']
The non-numeric columns are : ['address' 'state' 'country']

#1.Missing Values Check

CHecking for the presence of any missing values  in the datta

Checking for the presence of any missing values in the dataset. If missing values are present for a particular feature then depending upon the situation the feature may be either dropped (cases when a major amount of data is missing) or an appropiate value will be imputed in the feature column with missing values.

In [7]:
#Total number of missing values
cust_address.isnull().sum()

customer_id           0
address               0
postcode              0
state                 0
country               0
property_valuation    0
dtype: int64

#2. Inconsistency Check in Data

We will check whether ther is inconsistency data /typo error data in present in the categorical columns.
The columns to be checked are'address','postcode','state','country'

#2.1 State

In [8]:
cust_address['state'].value_counts()

NSW                2054
VIC                 939
QLD                 838
New South Wales      86
Victoria             82
Name: state, dtype: int64

Here there are inconsistent data in State column. For New South Wales and Victoria we have two values, one being the full name and the other being their short name. The State names should be standardised and columns with state as New South Wales will be replaced by NSW and columns with state as Victoria will be replaced by VIC.

In [9]:
#Function to replace full state names with their short forms.

def replace_state_names(state_name):

  #Making Short Form of State Names as Standards
  if state_name=='New South Wales':
    return 'NSW'
  elif state_name=='Victoria':
    return "VIC"
  else :
    return state_name

#Appling the above Function to State column
cust_address['state']=cust_address['state'].apply(replace_state_names)

After applying the above function the state name is standardised and there is no inconsistency in the state column.

In [10]:
cust_address['state'].value_counts()

NSW    2140
VIC    1021
QLD     838
Name: state, dtype: int64

#**2.2 Country**

In [11]:
cust_address['country'].value_counts()

Australia    3999
Name: country, dtype: int64

There is no inconsistency of data in the Country column.

#**2.3 Postcode**

The Postcode column looks perfect. There is no inconsistency / typo in the data.

In [12]:
cust_address[['address','postcode','state','country']].drop_duplicates()

                        address  postcode state    country
0            060 Morning Avenue      2016   NSW  Australia
1           6 Meadow Vale Court      2153   NSW  Australia
2            0 Holy Cross Court      4211   QLD  Australia
3           17979 Del Mar Point      2448   NSW  Australia
4              9 Oakridge Court      3216   VIC  Australia
...                         ...       ...   ...        ...
3994            1482 Hauk Trail      3064   VIC  Australia
3995  57042 Village Green Point      4511   QLD  Australia
3996     87 Crescent Oaks Alley      2756   NSW  Australia
3997           8194 Lien Street      4032   QLD  Australia
3998            320 Acker Drive      2251   NSW  Australia

[3999 rows x 4 columns]

#3. Duplication Checks
We need to ensure that there is no duplication of records in the dataset. This may lead to error in data analysis due to poor data quality. If there are duplicate rows of data then we need to drop such records.
For checking for duplicate records we need to firstly remove the primary key column of the dataset then apply drop_duplicates() function provided by Python.

In [13]:
# Dropping the primary key column i.e customer_id and storing into a temporary dataframe.
cust_address_dedupped = cust_address.drop('customer_id', axis=1).drop_duplicates()

print("Number of records after removing customer_id (pk), duplicates : {}".format(cust_address_dedupped.shape[0]))
print("Number of records in original dataset : {}".format(cust_address.shape[0]))

Number of records after removing customer_id (pk), duplicates : 3999
Number of records in original dataset : 3999

Since both the numbers are same. There are no duplicate records in the dataset

#**4. Exporting the Cleaned Customer Demographic Data Set to csv**

Currently the Customer Address dataset is clean. Hence we can export the data to a csv to continue our data analysis of Customer Segments by joining it to other tables.

In [14]:
cust_address.to_csv('/content/drive/MyDrive/Colab Notebooks/Customer_Segmentation/CustomerAddress_cleaned.csv',index=False)

#5.Checking for Master-Detail Record Counts

Checking with the Master Table (CustomerDemographic_Cleaned.csv) containing the entire Customer Data for the Customer IDs which are getting dropped from the Customer Address Dataset.
Basically these are the Customers who have an address but are not a part of the Demographics dataset yet.

In [15]:
cust_demo_detail = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Customer_Segmentation/CustomerDemographic_Cleaned.csv')

In [16]:
cust_demo_detail.head()

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,Age
0,1,Laraine,Medendorp,Female,93,1953-10-12,Executive Secretary,Health,Mass Customer,N,Yes,11.0,67
1,2,Eli,Bockman,Male,81,1980-12-16,Administrative Officer,Financial Services,Mass Customer,N,Yes,16.0,40
2,3,Arlin,Dearle,Male,61,1954-01-20,Recruiting Manager,Property,Mass Customer,N,Yes,15.0,67
3,4,Talbot,None,Male,33,1961-10-03,Missing,IT,Mass Customer,N,No,7.0,59
4,5,Sheila-kathryn,Calton,Female,56,1977-05-13,Senior Editor,Missing,Affluent Customer,N,Yes,8.0,44

In [17]:
print("Total Records in Customer_Demographic_Table : {}".format(cust_demo_detail.shape[0]))
print("Total Records in Customer_Address_Table : {}".format(cust_address.shape[0]))
print('In Demographic Table {} records are getting dropped due to data cleaning process in Demographic Table'
      .format(cust_address.shape[0]-cust_demo_detail.shape[0]))

Total Records in Customer_Demographic_Table : 3912
Total Records in Customer_Address_Table : 3999
In Demographic Table 87 records are getting dropped due to data cleaning process in Demographic Table

##Customer IDs in Address table getting dropped :

In [18]:
cust_drop = cust_address.merge(cust_demo_detail , left_on = 'customer_id', right_on='customer_id'
                     , how='outer')
cust_drop.head()

,customer_id,address,postcode,state,country,property_valuation,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,Age
0,1,060 Morning Avenue,2016.0,NSW,Australia,10.0,Laraine,Medendorp,Female,93.0,1953-10-12,Executive Secretary,Health,Mass Customer,N,Yes,11.0,67.0
1,2,6 Meadow Vale Court,2153.0,NSW,Australia,10.0,Eli,Bockman,Male,81.0,1980-12-16,Administrative Officer,Financial Services,Mass Customer,N,Yes,16.0,40.0
2,4,0 Holy Cross Court,4211.0,QLD,Australia,9.0,Talbot,None,Male,33.0,1961-10-03,Missing,IT,Mass Customer,N,No,7.0,59.0
3,5,17979 Del Mar Point,2448.0,NSW,Australia,4.0,Sheila-kathryn,Calton,Female,56.0,1977-05-13,Senior Editor,Missing,Affluent Customer,N,Yes,8.0,44.0
4,6,9 Oakridge Court,3216.0,VIC,Australia,9.0,Curr,Duckhouse,Male,35.0,1966-09-16,Missing,Retail,High Net Worth,N,Yes,13.0,54.0