In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math


from datetime import datetime,date
plt.style.use('ggplot')

In [5]:
#Loading the Transaction and customer Demographics Datasets

trans=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Customer_Segmentation/Transactions_Cleaned (1).csv')
cust=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Customer_Segmentation/CustomerDemographic_Cleaned.csv')

In [6]:
#Fetching first five records
trans.head(5)

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date,Profit
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,71.49,53.62,41245.0,17.87
1,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701.0,1702.55
2,3,37,402,2017-10-16,0.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361.0,1544.61
3,4,88,3135,2017-08-31,0.0,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10,36145.0,817.36
4,5,78,787,2017-10-01,1.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,42226.0,1055.82

In [7]:
print("Total records(rows) in the Transaction Dataset:  {}".format(trans.shape[0]))
print("Total features(columns) in the Transaction Dataset:  {}".format(trans.shape[1]))

Total records(rows) in the Transaction Dataset:  19803
Total features(columns) in the Transaction Dataset:  14

In [8]:
#Fettching First 5 Customers Democraphics records
cust.head(5)

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,Age
0,1,Laraine,Medendorp,Female,93,1953-10-12,Executive Secretary,Health,Mass Customer,N,Yes,11.0,70
1,2,Eli,Bockman,Male,81,1980-12-16,Administrative Officer,Financial Services,Mass Customer,N,Yes,16.0,43
2,3,Arlin,Dearle,Male,61,1954-01-20,Recruiting Manager,Property,Mass Customer,N,Yes,15.0,70
3,4,Talbot,None,Male,33,1961-10-03,Missing,IT,Mass Customer,N,No,7.0,62
4,5,Sheila-kathryn,Calton,Female,56,1977-05-13,Senior Editor,Missing,Affluent Customer,N,Yes,8.0,46

In [9]:
print("Total records(rows) in the customer demographics dataset:  {}".format(cust.shape[0]))
print("Total features(columns) in the customer demographics dataset:  {}".format(cust.shape[1]))

Total records(rows) in the customer demographics dataset:  3912
Total features(columns) in the customer demographics dataset:  13

In [10]:
# Merging both the Transaction Dataset and Customer Demographics Dataset based on customer_id.

merged_trans_cust = pd.merge(trans, cust, left_on='customer_id', right_on='customer_id', how='inner')

In [11]:
# Fetching the first 5 records of the merged dataset.

merged_trans_cust.head(5)

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,...,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,Age
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,...,Male,19,1955-01-11,Software Engineer I,Financial Services,Mass Customer,N,Yes,10.0,69
1,11065,1,2950,2017-10-16,0.0,Approved,Giant Bicycles,Standard,medium,medium,...,Male,19,1955-01-11,Software Engineer I,Financial Services,Mass Customer,N,Yes,10.0,69
2,18923,62,2950,2017-04-26,0.0,Approved,Solex,Standard,medium,medium,...,Male,19,1955-01-11,Software Engineer I,Financial Services,Mass Customer,N,Yes,10.0,69
3,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,...,Female,89,1979-02-04,Clinical Specialist,Health,Mass Customer,N,Yes,10.0,45
4,6862,4,3120,2017-10-05,0.0,Approved,Giant Bicycles,Standard,high,medium,...,Female,89,1979-02-04,Clinical Specialist,Health,Mass Customer,N,Yes,10.0,45

In [12]:
print("Total records (rows) in the Merged Dataset : {}".format(merged_trans_cust.shape[0]))
print("Total features (columns) in the Merged Dataset : {}".format(merged_trans_cust.shape[1]))

Total records (rows) in the Merged Dataset : 19354
Total features (columns) in the Merged Dataset : 26

In [13]:
merged_trans_cust.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19354 entries, 0 to 19353
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   transaction_id                       19354 non-null  int64
 1   product_id                           19354 non-null  int64
 2   customer_id                          19354 non-null  int64
 3   transaction_date                     19354 non-null  object
 4   online_order                         19354 non-null  float64
 5   order_status                         19354 non-null  object
 6   brand                                19354 non-null  object
 7   product_line                         19354 non-null  object
 8   product_class                        19354 non-null  object
 9   product_size                         19354 non-null  object
 10  list_price                           19354 non-null  float64
 11  standard_cost                        19354 non-null  float64
 12  product_first_sold_date              19354 non-null  float64
 13  Profit                               19354 non-null  float64
 14  first_name                           19354 non-null  object
 15  last_name                            19354 non-null  object
 16  gender                               19354 non-null  object
 17  past_3_years_bike_related_purchases  19354 non-null  int64
 18  DOB                                  19354 non-null  object
 19  job_title                            19354 non-null  object
 20  job_industry_category                19354 non-null  object
 21  wealth_segment                       19354 non-null  object
 22  deceased_indicator                   19354 non-null  object
 23  owns_car                             19354 non-null  object
 24  tenure                               19354 non-null  float64
 25  Age                                  19354 non-null  int64
dtypes: float64(6), int64(5), object(15)
memory usage: 4.0+ MB

The data-type of transaction_date column is not in date-time format. Hence the data-type of the column should be changed from object to datetime type.

In [14]:
merged_trans_cust['transaction_date']= pd.to_datetime(merged_trans_cust['transaction_date'])

#**1. RFM Analysis**

RFM (Recency, Frequency, Monetary) analysis is a behavior-based approach grouping customers into segments. It groups the customers on the basis of their previous purchase transactions. How recently, how often, and how much did a customer buy. RFM filters customers into various groups for the purpose of better service. There is a segment of customer who is the big spender but what if they purchased only once or how recently they purchased? Do they often purchase our product? Also, It helps managers to run an effective promotional campaign for personalized service.



*   Recency (R): Who have purchased recently? Number of days since last purchase (least recency)

*   Frequency (F): Who has purchased frequently? It means the total number of purchases. ( high frequency)

*   Monetary Value(M): Who have high purchase amount? It means the total money customer spent (high monetary value)

In [15]:
# Maximum Transaction Date or the latest transaction date.

max_trans_date = max(merged_trans_cust['transaction_date']).date()
max_trans_date

datetime.date(2017, 12, 30)

In [16]:
#Taking the last transaction date as a reference date for comparision and
#finding the number of days between a transaction date and lost transaction date to copute the recency.

comparison_date=datetime.strptime(str(max_trans_date),"%Y-%m-%d")

In [17]:
#Creating a RFM table that will contain all the values for recency ,frequency and Monetary data.

rfm_table = merged_trans_cust.groupby(['customer_id']).agg({'transaction_date': lambda date : (comparison_date - date.max()).days,
                                                            'product_id' : lambda prod_id : len(prod_id),
                                                            'Profit' : lambda p : sum(p)})

In [18]:
# The columns in rfm_table dataframe are not properly named. Renaming of the columns to appropiate name is needed

rfm_table.columns

Index(['transaction_date', 'product_id', 'Profit'], dtype='object')

In [19]:
# Renaming column names to appropiate names

rfm_table.rename(columns={'transaction_date' : 'recency',
                        'product_id' : 'frequency',
                        'Profit' : 'monetary'} , inplace=True)

In [20]:
# Dividing the recency, frequency and monetary into 4 quartiles (min, 25%, 50%, 75% and max).
# These values will help us to calculate RFM score for a customer and classify based on their RFM score.

rfm_table['r_quartile'] = pd.qcut(rfm_table['recency'], 4, ['4','3','2','1'])
rfm_table['f_quartile'] = pd.qcut(rfm_table['frequency'], 4, ['1','2','3','4'])
rfm_table['m_quartile'] = pd.qcut(rfm_table['monetary'], 4, ['1','2','3','4'])

In [21]:
# RFM_table dataset

rfm_table

             recency  frequency  monetary r_quartile f_quartile m_quartile
customer_id
1                  7         11   3018.09          4          4          3
2                128          3   2226.26          1          1          2
3                102          8   3362.81          1          4          3
4                195          2    220.57          1          1          1
5                 16          6   2394.94          4          2          2
...              ...        ...       ...        ...        ...        ...
3496             256          4   2045.84          1          1          2
3497              52          3   1648.32          2          1          1
3498             127          6   3147.33          1          2          3
3499              51          7   4955.25          2          3          4
3500             144          6   1785.86          1          2          1

[3416 rows x 6 columns]

In [22]:
# Caluclation of RFM Score.
# Max weightage is given to recency then frequency and then  monetary.

rfm_table['rfm_score'] = 100*rfm_table['r_quartile'].astype(int)+10*rfm_table['f_quartile'].astype(int)+rfm_table['m_quartile'].astype(int)

In [23]:
#Assigning a title to a customer.

#platinum corresponds to highest range of RFM score down to Bronze to lowest range of RFM score.

rfm_table['customer_title']=pd.qcut(rfm_table['rfm_score'],4,['Bronze','Silver','Gold','Platinum'])

In [24]:
#RFM  table dataset

rfm_table

,recency,frequency,monetary,r_quartile,f_quartile,m_quartile,rfm_score,customer_title
customer_id,,,,,,,,
1,7,11,3018.09,4,4,3,443,Platinum
2,128,3,2226.26,1,1,2,112,Bronze
3,102,8,3362.81,1,4,3,143,Bronze
4,195,2,220.57,1,1,1,111,Bronze
5,16,6,2394.94,4,2,2,422,Platinum
...,...,...,...,...,...,...,...,...
3496,256,4,2045.84,1,1,2,112,Bronze
3497,52,3,1648.32,2,1,1,211,Bronze
3498,127,6,3147.33,1,2,3,123,Bronze
3499,51,7,4955.25,2,3,4,234,Silver
3500,144,6,1785.86,1,2,1,121,Bronze

#**Merging both RFM Table with Transaction and Customer Tables**

The RFM_Table dataframe is merged with the Transactions and Customer Demographics datasets, to gain depper insights of Customer Segemnts along with transactions. The dataframes are joined based on customer_ids from both the datasets

In [25]:
cust_trans_rfm= pd.merge(merged_trans_cust,rfm_table,left_on='customer_id',right_on="customer_id",how='inner')

In [26]:
cust_trans_rfm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19354 entries, 0 to 19353
Data columns (total 34 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   transaction_id                       19354 non-null  int64
 1   product_id                           19354 non-null  int64
 2   customer_id                          19354 non-null  int64
 3   transaction_date                     19354 non-null  datetime64[ns]
 4   online_order                         19354 non-null  float64
 5   order_status                         19354 non-null  object
 6   brand                                19354 non-null  object
 7   product_line                         19354 non-null  object
 8   product_class                        19354 non-null  object
 9   product_size                         19354 non-null  object
 10  list_price                           19354 non-null  float64
 11  standard_cost                        19354 non-null  float64
 12  product_first_sold_date              19354 non-null  float64
 13  Profit                               19354 non-null  float64
 14  first_name                           19354 non-null  object
 15  last_name                            19354 non-null  object
 16  gender                               19354 non-null  object
 17  past_3_years_bike_related_purchases  19354 non-null  int64
 18  DOB                                  19354 non-null  object
 19  job_title                            19354 non-null  object
 20  job_industry_category                19354 non-null  object
 21  wealth_segment                       19354 non-null  object
 22  deceased_indicator                   19354 non-null  object
 23  owns_car                             19354 non-null  object
 24  tenure                               19354 non-null  float64
 25  Age                                  19354 non-null  int64
 26  recency                              19354 non-null  int64
 27  frequency                            19354 non-null  int64
 28  monetary                             19354 non-null  float64
 29  r_quartile                           19354 non-null  category
 30  f_quartile                           19354 non-null  category
 31  m_quartile                           19354 non-null  category
 32  rfm_score                            19354 non-null  int64
 33  customer_title                       19354 non-null  category
dtypes: category(4), datetime64[ns](1), float64(7), int64(8), object(14)
memory usage: 4.7+ MB

In [27]:
cust_trans_rfm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19354 entries, 0 to 19353
Data columns (total 34 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   transaction_id                       19354 non-null  int64
 1   product_id                           19354 non-null  int64
 2   customer_id                          19354 non-null  int64
 3   transaction_date                     19354 non-null  datetime64[ns]
 4   online_order                         19354 non-null  float64
 5   order_status                         19354 non-null  object
 6   brand                                19354 non-null  object
 7   product_line                         19354 non-null  object
 8   product_class                        19354 non-null  object
 9   product_size                         19354 non-null  object
 10  list_price                           19354 non-null  float64
 11  standard_cost                        19354 non-null  float64
 12  product_first_sold_date              19354 non-null  float64
 13  Profit                               19354 non-null  float64
 14  first_name                           19354 non-null  object
 15  last_name                            19354 non-null  object
 16  gender                               19354 non-null  object
 17  past_3_years_bike_related_purchases  19354 non-null  int64
 18  DOB                                  19354 non-null  object
 19  job_title                            19354 non-null  object
 20  job_industry_category                19354 non-null  object
 21  wealth_segment                       19354 non-null  object
 22  deceased_indicator                   19354 non-null  object
 23  owns_car                             19354 non-null  object
 24  tenure                               19354 non-null  float64
 25  Age                                  19354 non-null  int64
 26  recency                              19354 non-null  int64
 27  frequency                            19354 non-null  int64
 28  monetary                             19354 non-null  float64
 29  r_quartile                           19354 non-null  category
 30  f_quartile                           19354 non-null  category
 31  m_quartile                           19354 non-null  category
 32  rfm_score                            19354 non-null  int64
 33  customer_title                       19354 non-null  category
dtypes: category(4), datetime64[ns](1), float64(7), int64(8), object(14)
memory usage: 4.7+ MB

The datatypes of the columns looks fine.

#Creating an Age Group Feature

In [28]:
cust_trans_rfm['Age_group']=cust_trans_rfm['Age'].apply(lambda x:(math.floor(x/10)+1)*10)

#Creating a Detail Customer title / tag based on RFM Score

An extended version of customer title is made which divides the entire number of customers into 11 groups. The groups are mainly Platinum Customers, Very Loyal, Becoming Loyal, Recent Customers, Potential Customers, Late Bloomer, Loosing Customers, High Risk Customers, Almost Lost Customers, Evasive Customers and Lost Customers.
The demarkation of customers into the above mentioned groups is based on their RFM scores.

In [29]:
#Function as a lookup to appropiate customer title based on RFM score.

def cust_score_title_lkup(cols):
  rfm_score=cols[0]
  if rfm_score>=444:
    return 'Platinum Customer'
  elif rfm_score>=433 and rfm_score<444:
    return 'Very Loyal'
  elif rfm_score>=421 and rfm_score<433:
    return 'Becoming Loyal'
  elif rfm_score>=344 and rfm_score<421:
    return 'Recent loyal'
  elif rfm_score>=323 and rfm_score<344:
    return 'Potential loyal'
  elif rfm_score>=311 and rfm_score<323:
    return 'Late Bloomer'
  elif rfm_score>=224 and rfm_score<311:
    return 'Loosing Customer'
  elif rfm_score>=212 and rfm_score<224:
    return 'High Risk Customer'
  elif rfm_score>=124 and rfm_score<212:
    return 'Almost Lost Customer'
  elif rfm_score>=112 and rfm_score<124:
    return 'Evasive Customer'
  else :
    return 'Lost Customer'

In [30]:
# Applying the above functions and creating a new feature detail_cust_title

cust_trans_rfm['detail_cust_title']=cust_trans_rfm[['rfm_score']].apply(cust_score_title_lkup, axis=1)

In [31]:
# Function to provide ranks to the customers based on their title.

def get_rank(cols):

    title = cols[0]

    if title=='Platinum Customer':
        return 1
    elif title=='Very Loyal':
        return 2
    elif title == 'Becoming Loyal':
        return 3
    elif title == 'Recent Customer':
        return 4
    elif title=='Potential Customer':
        return 5
    elif title == 'Late Bloomer':
        return 6
    elif title == 'Loosing Customer':
        return 7
    elif title=='High Risk Customer':
        return 8
    elif title == 'Almost Lost Customer':
        return 9
    elif title == 'Evasive Customer':
        return 10
    else :
        return 11

In [32]:
# Applying the above functions and creating a new feature rank

cust_trans_rfm['rank']=cust_trans_rfm[['detail_cust_title']].apply(get_rank, axis=1)

#2. Exporting to CSV File